//launch options
//-novid -console -tickrate 128 -high -nojoy

//damage (obsolete)
//developer 1;
//con_filter_enable 2;
//con_filter_text_out "player:";
//con_filter_text "damage given";

//video
fps_max 200; 

//client 
rate 786432; 
mm_dedicated_search_maxping 80; 
gameinstructor_enable 0; 

cl_hud_color 8; 
cl_hud_radar_scale 1.2; 
cl_radar_scale 0.4; 
cl_radar_always_centered 0; 
cl_radar_icon_scale_min 0.4; 
cl_use_opens_buy_menu 0; 
cl_autowepswitch 0; 

//sound 
snd_deathcamera_volume 0; 
snd_mapobjective_volume 0.117109; 
snd_menumusic_volume 0.121501; 
snd_roundend_volume 0.062308; 
snd_roundstart_volume 0.119973; 
snd_tensecondwarning_volume 0.148263; 
snd_deathcamera_volume 0; 

//net graph
net_graph 1; 
net_graphheight 0; 
net_graphpos 180; 
net_graphproportionalfont 0; 

//keybinding
bind mwheeldown "+jump"; 
bind mouse4 "+jump;-attack;-attack2;"; 
bind mouse5 "+voicerecord"; 
bind alt "+radialradio2"; 
bind f "+lookatweapon;r_cleardecals"; 
bind h "noclip"; 
bind 6 "use weapon_c4;drop"; 
bind r "+reload;r_cleardecals"; 
bind z "slot10"; 
bind x "slot8"; 
bind c "slot6"; 
bind CAPSLOCK "slot7"; 

//sens
sensitivity 2; 
zoom_sensitivity_ratio_mouse 1.1; 
echo "4:3? m_yaw not set yet"

//xhair
cl_crosshair_drawoutline "0"; 
cl_crosshair_dynamic_maxdist_splitratio "0.300000"; 
cl_crosshair_dynamic_splitalpha_innermod "1"; 
cl_crosshair_dynamic_splitalpha_outermod "0.5"; 
cl_crosshair_dynamic_splitdist "1"; 
cl_crosshair_friendly_warning "1"; 
cl_crosshair_outlinethickness "1"; 
cl_crosshair_sniper_show_normal_inaccuracy "0"; 
cl_crosshair_sniper_width "1"; 
cl_crosshair_t "0"; 
cl_crosshairalpha "255"; 
cl_crosshaircolor "4"; 
cl_crosshaircolor_b "255"; 
cl_crosshaircolor_g "255"; 
cl_crosshaircolor_r "0"; 
cl_crosshairdot "1"; 
cl_crosshairgap "-4.000000"; 
cl_crosshairgap_useweaponvalue "0"; 
cl_crosshairsize "1.000000"; 
cl_crosshairstyle "5"; 
cl_crosshairthickness "0.900000"; 
cl_crosshairusealpha "1"; 
cl_fixedcrosshairgap "3"; 

//quickbuy
bind kp_end "buy vest; buy smokegrenade; buy flashbang; buy vesthelm"; 
bind kp_downarrow "buy ak47; buy vesthelm; buy smokegrenade; buy flashbang"; 
bind kp_pgdn "buy aug; buy vesthelm; buy smokegrenade; buy flashbang"; 
bind kp_leftarrow "buy awp; buy vest; buy smokegrenade; buy flashbang"; 
bind kp_5 "buy awp; buy vesthelm; buy smokegrenade; buy flashbang; buy flashbang"; 
bind kp_rightarrow "buy awp; buy vesthelm; buy smokegrenade; buy flashbang; buy flashbang; buy molotov; buy fn57; buy defuser; buy taser"; 
bind kp_home "buy vest; buy smokegrenade; buy flashbang; buy vesthelm"; 
bind kp_uparrow "buy smokegrenade; buy molotov; buy hegrenade; buy flashbang"; 
bind kp_pgup "buy smokegrenade; buy flashbang; buy hegrenade; buy flashbang"